Modification du profil d'un psy
betagouv/sante-psy pull request #222
Opened 2021-06-01 15:18 UTC by sandrica89

- Le psy ne peut pas modifier : son nom, prénom, diplôme, formations, etc. Ces données seront toujours mis à jour à partir de DS.
- Le psy peut modifier tous les autres champs (en particulier ceux qui s'affichent sur l'annuaire). Une fois qu'il a édité son profil, ces champs ne seront plus mis à jour à partir de DS.

2021-06-02 12:02 UTC, desoindx requested changes

2021-06-02 12:02 UTC, desoindx commented on test/test-dbPsychologists.js
> +      // should not fail
you could assert that we return 0 ?

2021-06-03 08:44 UTC, sandrica89 commented on controllers/psyProfileController.js
> +    .withMessage("Vous devez spécifier l'adresse de votre cabinet."),
They are mandatory on DS, so I kept it like that to avoid psy to remove the data.

2021-06-03 08:45 UTC, sandrica89 commented on controllers/psyProfileController.js
> +    const teleconsultation = Boolean(req.body.teleconsultation);
Indeed, now that it's a radio button, we should always send true or false.

- [ ] handle correctly teleconsultation field

2021-06-03 08:49 UTC, sandrica89 commented on db/psychologists.js
> +      const psyInDb = await getPsychologistById(psy.dossierNumber);
Trello card created.

2021-06-03 08:57 UTC, sandrica89 commented on db/psychologists.js
> +        return knex(psychologistsTable).update({
- [ ]  manage the editable field and the non editable one

2021-06-03 08:58 UTC, sandrica89 commented on db/psychologists.js
> +      } if (psyInDb.selfModified) {
The linter auto fix removes it.

2021-06-03 09:10 UTC, sandrica89 commented on frontend/src/components/Psychologist/Profile/PsyProfile.jsx
> +    e.preventDefault();
I don't understand, let's see this together

2021-06-03 13:40 UTC, desoindx commented on db/psychologists.js
> +
on peut mettre ca dans un service please ?

2021-06-03 13:40 UTC, desoindx commented on db/psychologists.js
> -        languages: addFrenchLanguageIfMissing(psy.languages),
shouldn't we let the languages ?

2021-06-03 13:40 UTC, desoindx commented on utils/access.ts
> +}
a good practice is to have a specific directory for our types
request.d.ts (d for declarative)

2021-06-04 14:01 UTC, desoindx approved these changes

2021-06-04 16:04 UTC, merged