Add auto verify to config
betagouv/sante-psy pull request #254
Opened 2021-06-16 08:16 UTC by desoindx

2021-06-16 08:31 UTC, sandrica89 commented on .env.ci
> +FEATURE_AUTO_VERIFY=true
No need it's just below

2021-06-16 08:32 UTC, sandrica89 commented on utils/config.js
> +  featureAutoVerify: process.env.FEATURE_AUTO_VERIFY || false,
Sorry I forgot this one in previous PR :(

2021-06-16 08:32 UTC, sandrica89 requested changes
Some new code can be removed

2021-06-16 08:40 UTC, desoindx commented
> Some new code can be removed

sorry !
c'est pas facile ce matin :p

2021-06-17 08:23 UTC, sandrica89 approved these changes

2021-06-17 09:03 UTC, merged