Properly await graphql mutation for manual launch
betagouv/sante-psy pull request #274
Opened 2021-06-21 15:56 UTC by desoindx

2021-06-21 17:30 UTC, sandrica89 commented on utils/graphql.js
> +const { resolve } = require('../frontend/config/webpack.dev.hot');
Wrong import

2021-06-21 17:31 UTC, sandrica89 commented on utils/graphql.js
> +    });
```suggestion
    const result = await graphQLClient.request(query, variables);
```

2021-06-22 09:27 UTC, sandrica89 commented on services/demarchesSimplifiees/autoAccept.js
> +  return Promise.resolve();
I think this can be remove.

2021-06-22 09:30 UTC, sandrica89 requested changes
See PR comment

2021-06-22 09:47 UTC, desoindx commented on services/demarchesSimplifiees/autoAccept.js
> +  return Promise.resolve();
ooops

2021-06-22 10:12 UTC, sandrica89 approved these changes

2021-06-22 10:53 UTC, merged