Refactor CSS usages
betagouv/sante-psy pull request #371
Opened 2021-08-05 13:24 UTC by desoindx

- Refactor Landing page to harmonize sections

- Use colors from DSFR (almost the same except statistics that are a bit different)

- Use new SearchableSelect from react-dsfr

2021-08-06 08:18 UTC, Evidorus commented on frontend/src/components/Landing/sectionTitle.cssmodule.scss
> +}
add space at the end ^^

2021-08-06 08:18 UTC, Evidorus commented on frontend/src/components/Landing/statistic.cssmodule.scss
>  }
Same here

2021-08-06 08:18 UTC, Evidorus commented on frontend/src/components/Landing/statistics.cssmodule.scss
>  }
and here

2021-08-09 09:40 UTC, sandrica89 requested changes
Colors on patient list for complete/incomplete files disappeared: 
![PR371-01](https://user-images.githubusercontent.com/68006779/128687146-ce037b66-bfa4-4324-890c-5835b6a0ec1c.jpg)

Searchable Select is too large compared to other inputs:
![PR371-02](https://user-images.githubusercontent.com/68006779/128687242-7908a90d-ecbf-446c-92a3-3111b277f6d6.jpg)
![PR371-03](https://user-images.githubusercontent.com/68006779/128687253-b7d7897e-4232-4a1e-ad51-70b6c1faa8e1.jpg)

2021-08-09 09:40 UTC, sandrica89 commented on frontend/src/components/Landing/statistic.cssmodule.scss
> -    color: #348375;
Note: with `--green-medium-700` it passes WCAG Color Contrast level AAA.

2021-08-09 09:40 UTC, sandrica89 commented on frontend/src/components/Landing/sectionTitle.cssmodule.scss
> +}
Ca sent la vengeance :D

2021-08-09 11:55 UTC, sandrica89 requested changes

2021-08-09 11:55 UTC, sandrica89 commented on frontend/src/components/Psychologist/Patients/patientRow.cssmodule.scss
> +}
* I would personally use `300` instead of `400`. It's really flashy ATM.
* On mobile, there is still no color in the icon.

2021-08-09 13:41 UTC, sandrica89 approved these changes

2021-08-09 13:48 UTC, merged