Psy cannot change assignedUniversity anymore
betagouv/sante-psy pull request #415
Opened 2021-09-09 14:04 UTC by desoindx

🔥

2021-09-09 16:24 UTC, sandrica89 approved these changes
Review ok but I couldn't test because I can't login (issue on review app seed probably)

2021-09-09 16:48 UTC, sandrica89 requested changes
I would add some space below the sentence "Vous êtes rattaché.."
![Selection_004](https://user-images.githubusercontent.com/68006779/132728264-cb68865c-4b02-4caa-a6b9-e8d38b37d296.jpg)

2021-09-09 17:25 UTC, desoindx commented
> I would add some space below the sentence "Vous êtes rattaché.."
> ![Selection_004](https://user-images.githubusercontent.com/68006779/132728264-cb68865c-4b02-4caa-a6b9-e8d38b37d296.jpg)

You always want to add space !!!  😉

2021-09-20 07:32 UTC, sandrica89 approved these changes

2021-09-20 07:39 UTC, merged