feat: Show first appointments and his specific price on bill
betagouv/sante-psy pull request #597
Opened 2024-01-08 16:18 UTC by Doniaab

2024-01-08 17:23 UTC, sandrica89 requested changes
Je n'ai pas testé le code, mais uniquement fait la revue.

2024-01-08 17:23 UTC, sandrica89 commented on frontend/src/components/Psychologist/Reimbursement/Bill.jsx
> +  useCommonEffect(setAppointments, false);
:green_circle: `useCommonEffect` ne permet pas de savoir ce que fait ce hook. Je l'aurai nommé `useAppointmentsByDate` par exemple.

2024-01-08 17:23 UTC, sandrica89 commented on frontend/src/components/Psychologist/Reimbursement/Billing.jsx
> +  useCommonEffect(setValuesByDate);
:green_circle: J'aurai tendance à ajouter le param `withPatients` ici et retirer la valeur par défaut au paramètre. Il n'y a à priori aucune raison de présumer que le comportement par défaut est d'inclure les patients (j'aurai même tendance à penser l'inverse).

2024-01-08 17:23 UTC, sandrica89 commented on frontend/src/components/Psychologist/Reimbursement/Bill.jsx
> +  const getFilteredDates = dates => Object.keys(dates).filter(date => {
:green_circle: 
```suggestion
  const getFilteredDates = valuesByDate => Object.keys(valuesByDate).filter(date => {
```
Ce ne sont pas des dates, c'est une map à ce niveau là et le nom `dates` peut porter à confusion

2024-01-08 17:23 UTC, sandrica89 commented on frontend/src/components/Psychologist/Reimbursement/Billing.jsx
> +  const getFilteredDates = dates => Object.keys(dates).filter(date => {
:green_circle: 
```suggestion
  const getFilteredDates = valuesByDate => Object.keys(valuesByDate).filter(date => {
```
Même remarque que plus haut

2024-01-08 17:23 UTC, sandrica89 commented on frontend/src/components/Psychologist/Reimbursement/Billing.jsx
> +                {` ${filteredFirstDates.reduce((accumulator, date) => accumulator + valuesByDate.firstAppointments[date], 0)} `}
:green_circle: On pourrait extraire cette logique dans une méthode qui serait utilisé pour `valuesByDate.appointments` et `valuesByDate.firstAppointments`. On évite ainsi la duplication et simplifie cette partie.

Edit : on retrouve aussi cette logique dans les `render` de `frontend/src/components/Psychologist/Reimbursement/BillingTable.jsx`, donc on peut même envisager de l'extraire dans un autre fichier.

2024-01-08 17:23 UTC, sandrica89 commented on frontend/src/components/Psychologist/Reimbursement/BillingTable.jsx
> +        const totalFirstAppointments = nbFirstAppointments * 40;
:green_circle: On peut extraire ces magic numbers dans des constantes : 
```suggestion
        const FIRST_APPOINTMENT_TTC = 40;
        const NEXT_APPOINTMENT_TTC = 30;
        const totalAppointments = (nbAppointments - nbFirstAppointments) * NEXT_APPOINTMENT_TTC;
        const totalFirstAppointments = nbFirstAppointments * FIRST_APPOINTMENT_TTC;
```

(Je les met au dessus pour l'exemple, mais elles peuvent être mise en haut du fichier)

2024-01-08 17:23 UTC, sandrica89 commented on frontend/src/components/Psychologist/Reimbursement/commonEffect.jsx
> +      agent.Appointment.getFirstAppointments().then(firstAppointments => {
:orange_circle: On attend que "get appointments" soit terminé pour appeler "get first appointments". J'ai l'impression qu'on pourrait les appeler en parallèle. Si oui, on peut faire ainsi : 
```
Promise.all([
  agent.Appointment.get(), 
  agent.Appointment.getFirstAppointments()
])
.then((results) => {
  const appointments = results[0]; // actuellement cette variable est "response"
  const firstAppointments = results[1];
  // ....
});
```

2024-01-08 17:23 UTC, sandrica89 commented on frontend/src/components/Psychologist/Reimbursement/commonEffect.jsx
> +      });
:green_circle: Cela n'a d'intérêt que si `withPatients`. On peut donc déplacer ce bout de code dans le `if (withPatients) {` plus bas.

2024-01-09 09:58 UTC, Doniaab commented on controllers/appointmentsController.ts
> +  const startCycle = new Date('2024-01-01');
- J'aurais tendance à dire que si elle est pas amenée a changer ça a pas trop d'utilité de la mettre en variable d'environnement. Peut être dans un fichier config sinon
- tu as raisons, je vais mettre la date de startCycle en UTC et convertir la date de la seance en UTC pour éviter les problèmes

2024-01-09 10:10 UTC, Doniaab commented on controllers/appointmentsController.ts
> +    const cycle = (appointmentDate.getMonth() >= 9 && appointmentDate.getMonth() <= 12)
- j'ai un doute parce que dans la description de la fonction dans la lib on a bien "Gets the month of a Date object using Universal Coordinated Time (UTC)" et c'est bien getMonth() qui est utilisé un peu partout dans le code pour les dates des séances jusqu'à maintenant. Je pense surtout qu'il faut que je m'assure que la date de la séance soit en UTC avant de faire le getMonth(), je vais changer ça

- my bad je confirme que pour janvier getMonth renvoie 0, j'ajoute les constantes

2024-01-09 14:36 UTC, sandrica89 commented on frontend/src/components/Psychologist/Reimbursement/commonEffect.jsx
:green_circle: Tu peux renommer ce fichier par `appointmentsByDate` et tu pourrais créer un dossier `hooks` dans lequel tu mets ce fichier et d'autres custom hooks à venir. (Si ça t'aide à les retrouver par exemple).

2024-01-09 14:36 UTC, sandrica89 commented on frontend/src/components/Psychologist/Reimbursement/commonEffect.jsx
> +    // });
:red_circle: Supprimer ce code commenté

2024-01-09 14:36 UTC, sandrica89 commented on test/controllers/appointmentsController.spec.ts
> +      // Créer le psy une seule fois avant l'exécution des tests
:green_circle: Je ne pense pas que ce commentaire soit utile, le code est clair non ?

2024-01-09 14:36 UTC, sandrica89 commented on utils/appointments.ts
:green_circle: Je l'aurai plutôt mis dans `services` que `utils`. 
Dans l'idée, `services` contient des services avec de la logique métier, et `utils` des services utilitaires qui pourrait potentiellement être utilisé dans d'autres projets.

2024-01-09 14:36 UTC, sandrica89 commented on utils/appointments.ts
> +  const startCycle = new Date('2024-01-01T00:00:00Z');
:green_circle: Si tu suis la convention qui met en majuscule les constantes, tu peux le faire ici aussi : 
```suggestion
  const START_CYCLE_DATE = new Date('2024-01-01T00:00:00Z');
```

2024-01-09 14:37 UTC, sandrica89 commented on controllers/appointmentsController.ts
> +  const startCycle = new Date('2024-01-01');
Tu as pu testé que ta comparaison en UTC est ok ? (J'ai déjà eu pas mal de soucis avec les heures donc je me méfie toujours)

2024-01-09 14:46 UTC, sandrica89 commented on test/controllers/appointmentsController.spec.ts
> +      });
:orange_circle: Tu fais ça pour créer des séances pour ce patient ? 
Si oui, pas la peine de faire un appel API ici, ce n'est pas ce que tu testes, tu établis ton cas de test.
Tu peux donc faire : 
`await dbAppointments.insert(new Date('2024-01-03'), patientWithAppointments.id, psy.dossierNumber);`

2024-01-09 14:48 UTC, sandrica89 commented on test/controllers/appointmentsController.spec.ts
> +      );
:orange_circle: C'est l'élément que tu veux tester ici ?
Si oui, tu testes `dbAppointments` et non `appointmentsController`, ce n'est donc pas dans ce fichier que tu dois ajouter ton test mais dans `test/db/appointments.spec.ts`. 
Ici, on teste les appels API, par exemple : `GET /appointments`

2024-01-09 16:17 UTC, Doniaab commented on test/controllers/appointmentsController.spec.ts
> +      );
non je voulais surtout tester la logique utilisée dans appointmentController pour récupérer les premières séances donc la combinaison du getAll avec extractFirstAppointments.  ça me semblait logique de faire ça à cet endroit du coup puisque ce sont les tests de appointmentsController, qu'en penses-tu ?

2024-01-09 18:03 UTC, Doniaab commented on test/controllers/appointmentsController.spec.ts
> +      );
modification faite

2024-01-09 18:03 UTC, Doniaab commented on test/controllers/appointmentsController.spec.ts
> +      });
modification faite

2024-01-09 18:03 UTC, Doniaab commented on utils/appointments.ts
> +  const startCycle = new Date('2024-01-01T00:00:00Z');
modification faite

2024-01-09 18:03 UTC, Doniaab commented on utils/appointments.ts
modification faite

2024-01-09 18:04 UTC, Doniaab commented on test/controllers/appointmentsController.spec.ts
> +      // Créer le psy une seule fois avant l'exécution des tests
modification faite

2024-01-09 18:04 UTC, Doniaab commented on frontend/src/components/Psychologist/Reimbursement/commonEffect.jsx
> +    // });
modification faite

2024-01-09 18:04 UTC, Doniaab commented on frontend/src/components/Psychologist/Reimbursement/commonEffect.jsx
modification faite

2024-01-09 18:05 UTC, Doniaab commented on controllers/appointmentsController.ts
> +  const startCycle = new Date('2024-01-01');
j'ai fait différents tests, ça semble good ! en s'assurant d'avoir les date en utc lors de la comparaison ça évite les problèmes

2024-01-10 14:52 UTC, sandrica89 approved these changes

2024-01-22 10:27 UTC, merged